openapi: 3.0.0
info:
  version: 1.0.0
  title: Contact Management API
  description: API for managing contacts
servers:
  - url: http://localhost:8080
paths:
  /professional:
    get:
      summary: Retrieve all contacts
      responses:
        "200":
          description: A list of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Contact"
    post:
      summary: Create a new contact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "201":
          description: Contact created successfully

  /professional/{id}:
    get:
      summary: Retrieve a contact by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single contact
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Contact"
        "404":
          description: Contact not found
    put:
      summary: Update a contact by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        "204":
          description: Contact updated successfully
    delete:
      summary: Delete a contact by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Contact deleted successfully

components:
  schemas:
    Contact:
      type: object
      required:
        - firstName
        - lastName
        - email
        - favoriteColor
        - birthday
      properties:
        firstName:
          type: string
          example: Alice
        lastName:
          type: string
          example: Johnson
        email:
          type: string
          format: email
          example: alice@example.com
        favoriteColor:
          type: string
          example: Green
        birthday:
          type: string
          format: date
          example: 1995-04-21
